# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 30b4502969a937156125c951813b63a5b4a232650f1ac613b40a59e14b4fa66dbf3d5d666f3aa5a8781469126e15a69f553fe04d02109d0e9f53f9df7edfc6cd

test:
  secret_key_base: 1c14a07051d2ff4140183193bb74da8e5724d0bf13e310cb6859398902d44aa91f0a5686ad86d982eb5f9dee890f2237f73ebf40fa2f236083f91014903b017d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
